import * as moment from 'moment';
export class CONSTANT {
    public static instanceTypes: [
        't2.nano',
        't2.micro',
        't2.small',
        't2.medium',
        't2.large',
        'm4.large',
        'm4.xlarge',
        'm4.2xlarge',
        'm4.4xlarge',
        'm4.10xlarge',
        'm4.16xlarge',
        'm3.medium',
        'm3.large',
        'm3.xlarge',
        'm3.2xlarge',
        'c4.large',
        'c4.xlarge',
        'c4.2.xlarge',
        'c4.4.xlarge',
        'c4.8.xlarge',
        'c3.large',
        'c3.xlarge',
        'c3.2xlarge',
        'c3.4xlarge',
        'c3.8.xlarge',
        'p2.xlarge',
        'p2.8xlarge',
        'p2.16xlarge',
        'g2.2xlarge',
        'g2.8xlarge',
        'x1.16large',
        'x1.32xlarge',
        'r3.large',
        'r3.xlarge',
        'r3.2xlarge',
        'r3.4xlarge',
        'r3.8xlarge',
        'i2.xlarge',
        'i2.2xlarge',
        'i2.4xlarge',
        'i2.8xlarge',
        'd2.xlarge',
        'd2.2xlarge',
        'd2.4xlarge',
        'd2.8xlarge'
      ];

    public static regions: [
        {
          id: 'us-east-1',
          name: 'US East (N. Virginia)',
          children: [
            // {id: 'us-east-1b'},
            {id: 'us-east-1c'}
            // {id: 'us-east-1d'},
            // {id: 'us-east-1e'}
          ]
        },
        {
          id: 'us-west-2',
          name: 'US West (Oregon)'
        },
        {
          id: 'us-west-1',
          name: 'US West (N. California)'
        },
        {
          id: 'eu-west-1',
          name: 'EU (Ireland)'
        },
        {
          id: 'eu-central-1',
          name: 'EU (Frankfurt)'
        },
        {
          id: 'ap-southeast-1',
          name: 'Asia Pacific (Singapore)'
        },
        {
          id: 'ap-northeast-1',
          name: 'Asia Pacific (Tokyo)'
        },
        {
          id: 'ap-northeast-2',
          name: 'Asia Pacific (Seoul)'
        },
        {
          id: 'ap-southeast-2',
          name: 'Asia Pacific (Sydney)'
        },
        {
          id: 'sa-east-1',
          name: 'South America (São Paulo)'
        },
        {
          id: 'us-gov-west-1',
          name: 'AWS GovCloud (US)'
        },
        {
          id: 'cn-north-1',
          name: 'China (Beijing)'
        }
      ];
    public static avaiableZones = [];

    public static StaticParams = {
      tableQuery : {
        order: '-id',
        limit: 16,
        page: 1,
        offset: 0,
      },
      tableOptions: {
        rowSelection: true,
        multiSelect: true,
        autoSelect: true,
        decapitate: false,
        largeEditDialog: false,
        boundaryLinks: false,
        limitSelect: true,
        pageSelect: true,
        limitOptions: [16, 24],
        label: {
          page: 'Page:',
          rowsPerPage: 'Per Page:',
          of: '/'
        }
      },
      // configStatusIds: ['be-terminate', 'stop', 'runnning', 'started  '];
      configStatuses: [
        {
          id: 'terminate',
          name: 'Be Terminate',
          color: ''
        },
        {
          id: 'stop',
          name: 'Stop',
          color: ''
        },
        {
          id: 'running',
          name: 'Running',
          color: ''
        },
        {
          id: 'started',
          name: 'Started',
          color: ''
        },
      ],
      configTypes: [
        {
          id: 1,
          name: 'Type 1'
        },
        {
          id: 2,
          name: 'Type 2'
        },
        {
          id: 3,
          name: 'Type 3'
        },
        {
          id: 4,
          name: 'Type 4'
        }
      ],
      userdefinedProperties: [
        {key:'jmeter.save.saveservice.output_format', value: 'csv', name: 'Output Format', isBoolean: false},
        {key:'jmeter.save.saveservice.print_field_names', value: true, name: 'Print Field Names', isBoolean: true},
        {key:'jmeter.save.saveservice.assertion_results_failure_message', value: true, name: 'Assertion results failure message', isBoolean: true},
        {key:'jmeter.save.saveservice.data_type', value: true, name: 'Data type', isBoolean: true},
        {key:'jmeter.save.saveservice.label', value: true, name: 'Label', isBoolean: true},
        {key:'jmeter.save.saveservice.response_code', value: true, name: 'Response code', isBoolean: true},
        {key:'jmeter.save.saveservice.response_data.on_error', value: false, name: 'Response data on error', isBoolean: true},
        {key:'jmeter.save.saveservice.response_message', value: true, name: 'Response message', isBoolean: true},
        {key:'jmeter.save.saveservice.successful', value: true, name: 'Successful', isBoolean: true},
        {key:'jmeter.save.saveservice.thread_name', value: true, name: 'Thread name', isBoolean: true},
        {key:'jmeter.save.saveservice.time', value: true, name: 'Time', isBoolean: true},
        {key:'jmeter.save.saveservice.subresults', value: true, name: 'Subresults', isBoolean: true},
        {key:'jmeter.save.saveservice.assertions', value: true, name: 'Assertions', isBoolean: true},
        {key:'jmeter.save.saveservice.latency', value: true, name: 'Latency', isBoolean: true},
        {key:'jmeter.save.saveservice.connect_time', value: false, name: 'Connect_time', isBoolean: true},
        {key:'jmeter.save.saveservice.samplerData', value: false, name: 'SamplerData', isBoolean: true},
        {key:'jmeter.save.saveservice.responseHeaders', value: false, name: 'Response Headers', isBoolean: true},
        {key:'jmeter.save.saveservice.requestHeaders', value: false, name: 'Request Headers', isBoolean: true},
        {key:'jmeter.save.saveservice.encoding', value: false, name: 'Encoding', isBoolean: true},
        {key:'jmeter.save.saveservice.bytes', value: true, name: 'Bytes', isBoolean: true},
        {key:'jmeter.save.saveservice.url', value: true, name: 'Url', isBoolean: true},
        {key:'jmeter.save.saveservice.filename', value: false, name: 'File name', isBoolean: true},
        {key:'jmeter.save.saveservice.hostname', value: false, name: 'Host name', isBoolean: true},
        {key:'jmeter.save.saveservice.thread_counts', value: true, name: 'Thread counts', isBoolean: true},
        {key:'jmeter.save.saveservice.sample_count', value: false, name: 'Sample count', isBoolean: true},
        {key:'jmeter.save.saveservice.idle_time', value: true, name: 'Idle time', isBoolean: true},
        {key:'summariser.influx.out.enabled', value: true, name: 'Enalbe Influx out', isBoolean: true},
      ]
    }

    public static configData = [
      {
        "grid_id": '1',
        "grid_name": "smoke_test",
        "description":"description of grid",
        "created_by":"Created By User",
        "createdAt": moment().format(),
        "updated_by": "Updated By User",
        "updatedAt": moment().format(),
        "bucket_name":"loadswarmjmx",
        "pem_file_path":"pem/qaDashboard.pem",
        "children" : [
          {
            "grid_id": "1",
            "grid_child_id": "1_1",
            "instancesCount":"10",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_2",
            "instancesCount":"10",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_3",
            "instancesCount":"10",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_4",
            "instancesCount":"4",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_5",
            "instancesCount":"2",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_6",
            "instancesCount":"14",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_7",
            "instancesCount":"1",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_8",
            "instancesCount":"5",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "1_9",
            "instancesCount":"100",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
        ]
      },
      {
        "grid_id": '2',
        "grid_name": "GRID 2",
        "description":"description of grid",
        "created_by":"Created By User",
        "createdAt": moment().format(),
        "updated_by": "Updated By User",
        "updatedAt": moment().format(),
        "children" : [
          {
            "grid_id": "1",
            "grid_child_id": "2_1",
            "instancesCount":"9",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "2_2",
            "instancesCount":"3",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "2_3",
            "instancesCount":"1",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "2_4",
            "instancesCount":"6",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "2_5",
            "instancesCount":"2",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
          {
            "grid_id": "1",
            "grid_child_id": "2_6",
            "instancesCount":"8",
            "instanceType":"type",
            "ImageId":"ami",
            "MinCount":"default to 1 no need to show this in UI",
            "MaxCount":"default to 1 no need to show this in UI",
            "KeyName":"File Name",
            "region":"Region name",
            "SubnetId":"SubnetID value here",
            "AvailabilityZone":"availability value here",
            "reserved_instance":"reserved instance or not",
            "PlacementGroup":"placement group here",
            "DeviceName":"device name default to /dev/xvda",
            "EbsVolumeSize":"instance ebs volume in gb",
            "EbsDeleteOnTermination":"true or false",
            "EbsVolumeType":"instance ebs volume type",
            "EbsIops":"this is required if EbsVolumeType is io1 otherwise this is not of much value",
            "duration":"100",
            "delay":"100",
            "instance_close_status":"to terminate or stop",
            "created_by":"",
            "createdAt":"",
            "updated_by":"",
            "updatedAt":"",
          },
        ]
      },
    ];

    public static globalUtils = {
      generateUUID: function() {
          var d = new Date().getTime();
          var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
              var r = (d + Math.random()*16)%16 | 0;
              d = Math.floor(d/16);
              return (c=='x' ? r : (r&0x3|0x8)).toString(16);
          });
          return uuid;
      }
  };

}